on:
  push:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Enable dockerd --experimental for docker build --squash
      run: |
        if [ -f /etc/docker/daemon.json ]; then
        	DOCKERD_CONFIG=$(sudo cat /etc/docker/daemon.json)
        else
        	DOCKERD_CONFIG={}
        fi
        DOCKERD_CONFIG=$(jq '.+{experimental:true}' <<<"${DOCKERD_CONFIG}")
        sudo tee /etc/docker/daemon.json <<<"${DOCKERD_CONFIG}"
        sudo systemctl restart docker
    - name: Build docker image
      run: |
        cp dehydrated/dehydrated docker/
        IMAGE_ID=$(docker build --squash --quiet docker)
        echo "IMAGE_ID=$IMAGE_ID" >>$GITHUB_ENV
    # TODO: test
    - name: Push docker image
      if: github.ref == 'refs/heads/master'
      env:
        IMAGE_PATH: registry-1.docker.io/youfu/dehydrated:latest
        REGISTRY_USERNAME: youfu
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        docker login --username "${REGISTRY_USERNAME}" --password "${REGISTRY_PASSWORD}" "${IMAGE_PATH%%/*}"
        docker tag "${IMAGE_ID}" "${IMAGE_PATH}"
        docker push "${IMAGE_PATH}"
