on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - master
concurrency: build
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_PATH: ghcr.io/${{ github.repository_owner }}/dehydrated:${{ github.event_name == 'push' && ( github.ref_name == 'master' && 'latest' || github.ref_name ) || format('pr-{0}', github.event.pull_request.number) }}
    steps:
    - uses: zhangyoufu/actions/checkout@main
      with:
        submodules: true
    - name: Install qemu-user-static as binfmt handler
      run: |-
        sudo apt-get update
        sudo apt-get install -y -o=Dpkg::Use-Pty=0 binfmt-support qemu-user-static
    - name: Register BuildKit node
      run: docker buildx create --driver docker-container --use
    - name: Build docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 --tag "$IMAGE_PATH" --build-context dehydrated=dehydrated - < Dockerfile
    - name: Push docker image
      if: github.event_name == 'push'
      env:
        REGISTRY_USERNAME: ${{ github.actor }}
        REGISTRY_PASSWORD: ${{ github.token }}
      run: |-
        docker login --username "${REGISTRY_USERNAME}" --password "${REGISTRY_PASSWORD}" "${IMAGE_PATH%%/*}"
        docker buildx build --platform linux/amd64,linux/arm64 --tag "$IMAGE_PATH" --build-context dehydrated=dehydrated --push - < Dockerfile
